### ISSUE TITLE
Placeholder text line is being cut off inside the 'Dropdown' component

### ISSUE THREAD

**Issue by blidden** [gsysko/Zketch#3]
It looks as though the left hand side of the placeholder bar inside the dropdown component is being cut off. Comparing it side by side with the standard text input you can see the border radius isn't consistent across both. Screenshot attached as reference. Thanks!
![Dropdown v Text input](https://user-images.githubusercontent.com/4605839/119581733-7eb7fb80-be06-11eb-8b83-050da993084f.png)

**Comment by gsysko** [comment]
Fortunately this was also addressed by improving the starting alignment of the string 🙌
